<Project>
  <PropertyGroup>
    <DotnetVersion>net10.0</DotnetVersion>
    <AvaloniaVersion>11.2.3</AvaloniaVersion>
    <CefRedistVersion>75.1.0</CefRedistVersion>
    <CefRedistLinuxVersion>75.1.0</CefRedistLinuxVersion>
    <CefRedistOSXVersion>75.1.0</CefRedistOSXVersion>
  </PropertyGroup>
</Project>
