<Project>
  <PropertyGroup>
    <DotnetVersion>net10.0</DotnetVersion>
    <AvaloniaVersion>11.3.14</AvaloniaVersion>
    <CefRedistVersion>147.0.10</CefRedistVersion>
    <CefRedistLinuxVersion>147.0.10</CefRedistLinuxVersion>
    <CefRedistOSXVersion>147.0.10</CefRedistOSXVersion>
  </PropertyGroup>
</Project>
