<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>MusicPlayerWeb</AssemblyName>
    <RootNamespace>MusicPlayerWeb</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationIcon>play_button.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <!-- Avalonia packages -->
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="CefGlue.Common" />
    <PackageReference Include="CefGlue.Avalonia" />
    <!-- JSON -->
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../MusicPlayer/MusicPlayer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="play_button.ico" />
  </ItemGroup>

</Project>
